name: pokeapi_dart_client
version: 1.0.0+1
description: A fully fledged pokéapi dart client.
homepage: https://github.com/lordkleiton/pokeapi_dart_client

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.1
