name: pokeapi_dart_lib
version: 1.0.2
description: A fully fledged pokéapi dart library.
homepage: https://github.com/lordkleiton/pokeapi_dart_lib

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.1
